### ISSUE TITLE
Error: Fragment not attached to Activity

### ISSUE THREAD

**Issue by ismaeltoe** [fcannizzaro/material-stepper#25]
My app worked fine when I was using 1.0.5 version. After upgrade to 1.0.9, I got this error [https://gist.github.com/ismaeltoe/6713ff5c128e98301a8ec403a611741c](https://gist.github.com/ismaeltoe/6713ff5c128e98301a8ec403a611741c)

**Comment by ismaeltoe** [comment]
When upgrading to 1.0.9, I get that error. And when (re)downgrading to 1.0.5, I got another error but when I restart Android Studio, I don't get that error again. It seems that the problem comes from Android Studio and/or Gradle. I will try again with 1.0.9 if I have enough time to see what happen.

**Comment by ismaeltoe** [comment]
I have tried un another project. This time, I directly used 1.0.9 version the first time but got the same error. But it works with 1.0.5. Weird.

**Comment by alashow** [comment]
It's because of you `getString()` in your fragment (in `name()`, `error()`, `optional()`). Library needs to fix this, because it's calling these methods same time as attaching it ([source code](https://github.com/fcannizzaro/material-stepper/blob/master/library/src/main/java/com/github/fcannizzaro/materialstepper/style/TabStepper.java#L110)).

I hope someone will fix it.

But for now, instead of directly calling `getString()` from fragment, you can use Application context. 
Create Application class for your app and add context getter static method. See http://stackoverflow.com/q/8262279/2897341 and  documentation http://developer.android.com/reference/android/app/Application.html 

then use it like this:
```java
@Override
    public String optional() {
        return  MyApp.getContext().getString(R.string.optional);
    }

@Override
    public String error() {
        return  MyApp.getContext().getString(R.string.error);
    }

    @Override
    public String name() {
        return MyApp.getContext().getString(R.string.name);
    }
```

Hope this helps!

**Comment by ismaeltoe** [comment]
Thank you but it doesn't solve the problem.

To sum up:

- When using 1.0.9, get this error (always) [https://gist.github.com/ismaeltoe/4b918624b262d3ab2cd43311c76f8a0c](https://gist.github.com/ismaeltoe/6713ff5c128e98301a8ec403a611741c)

- When using 1.0.5, get this error (only after downgrading from 1.0.9): [https://gist.github.com/ismaeltoe/4b918624b262d3ab2cd43311c76f8a0c](https://gist.github.com/ismaeltoe/4b918624b262d3ab2cd43311c76f8a0c) and works after rebuilding the project.

**Comment by alashow** [comment]
Try this, In my fork I fixed getString method on `AbstractStep` ([jitpack](https://jitpack.io/#alashow/material-stepper/1.1.0)):
```java
compile 'com.github.alashow:material-stepper:1.1.0'
```
I sent pull request, but you can use this until it's merged.

**Comment by fcannizzaro** [comment]
@alashow thanks :+1:
